module: RKTableAdapter
author: DaskiOFF
author_url: http://t.me/daskioff
github_url: https://github.com/DaskiOFF/RKTableAdapter
clean: true

copyright: '© 2018 [DaskiOFF](http://t.me/daskioff) under MIT License'

swift_version: 4.1

custom_categories:
  - name: Main Table
    children:
    - TableViewAdapter
    - TableAdapterCallbacks
    - TableAdapterScrollViewCallbacks
    - TableList
    - TableSection
    - TableRow

  - name: Main Collection
    children:
    - CollectionViewAdapter
    - CollectionAdapterCallbacks
    - CollectionAdapterScrollViewCallbacks
    - CollectionList
    - CollectionSection
    - CollectionItem

  - name: Cell ViewModel
    children:
    - CellVM

  - name: Cell
    children:
    - ConfigurableCell

  - name: Internal
    children:
    - BindingCell
    - ConfigureCell
    - RowConfigurable
    - RowHeightComputable

  - name: Standard Rows
    children:
    - TableRowSwitch
    - TableSwitchCell
    - TableSwitchCellVM
